# Generated by Django 5.1.6 on 2025-02-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
